import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, useForm } from '@inertiajs/react';

// The 'news' prop comes from your NewsController.php edit() method
export default function Edit({ auth, news }) {

    // We are not using the form yet, but this sets up the update logic
    const { data, setData, put, processing, errors } = useForm({
        title: news.title,
        content: news.content,
        // ... include other fields like image_path if needed
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        // The put method handles the submission to the 'admin.news.update' route
        // This route is automatically generated by Route::resource()
        put(route('admin.news.update', news.id));
    };

    return (
        <AuthenticatedLayout
            user={auth.user}
            header={<h2 className="font-semibold text-xl text-gray-800 leading-tight">Edit News: {news.title}</h2>}
        >
            <Head title={`Edit News: ${news.title}`} />

            <div className="py-12">
                <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                    <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                        <div className="p-6 text-gray-900">
                            <h3 className="text-xl font-bold mb-4">Editing News Item ID: {news.id}</h3>

                            {/* TODO: Add your actual form fields here later */}
                            <form onSubmit={handleSubmit}>
                                <div className="mb-4">
                                    <label className="block text-gray-700 text-sm font-bold mb-2">Title:</label>
                                    <input
                                        type="text"
                                        value={data.title}
                                        onChange={(e) => setData('title', e.target.value)}
                                        className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                    />
                                    {errors.title && <p className="text-red-500 text-xs mt-1">{errors.title}</p>}
                                </div>
                                <button type="submit" disabled={processing} className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded">
                                    {processing ? 'Saving...' : 'Save Changes'}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}
